CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 10, 6} available.
Started basinhopping at 2021-01-16 19:38:47.533505 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/chain/periodic/own_graph/ops/energy/18', 'n_par': 18, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'energy', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2021-01-16 19:38:47.533505', 'complete_graph': [(1, 2), (3, 4), (5, 6), (7, 8), (9, 10), (11, 12), (13, 14), (15, 16), (17, 0), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(1, 2), (3, 4), (5, 6), (7, 8), (9, 10), (11, 12), (13, 14), (15, 16), (17, 0)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
......................................................................................................................................................................................................................................./home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
 
==========================================================================================
Finished basinhopping of  /home/jkgpu/HVQE/data/chain/periodic/own_graph/ops/energy/18 at 2021-01-16 19:49:28.764004 UTC, with
 
{'path': '/home/jkgpu/HVQE/data/chain/periodic/own_graph/ops/energy/18', 'n_par': 18, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'energy', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
init_par = [-0.00034960209033813207, -0.00010097293650163265, 0.00043493098974465834, -0.00023091657455906066, 0.00016603858390034937, 0.0004187958036004464, 8.013424600519098e-05, -0.0002578713075146262, -0.0004280524671838634, -0.0004842805526373657, -0.00038592846874576324, 4.099646201363217e-05, 5.22067424948158e-05, -0.0001913606008640848, -0.00026976546487860587, 0.00021090152627906155, -0.00012367412077259158, 0.0003479611849235378]
 
RESULTS:
--------
E_VQE = -7.948544050135836
inf_VQE = 0.13907641427780593
n_fn_calls = 231
Wall-clock time 0.17794026182757483 hours
 
For more output, see /home/jkgpu/HVQE/data/chain/periodic/own_graph/ops/energy/18/output.txt
Plots of output saved in /home/jkgpu/HVQE/data/chain/periodic/own_graph/ops/energy/18
End of HVQE.py
==========================================================================================
